### PR TITLE
Fix https://bugreports.qt.io/browse/QTBUG-2390

### PR DESCRIPTION
**Pull request by pretyman**

### CODE REVIEW

**Comment by pretyman** [comment]
Hi, I'm opening here the pull request to fix this Qt issue because I have to first study their contribution process to send the fix upstream

**Comment by pretyman** [comment]
Reviewing process was quicker than I thought. I will close this and re-open at a later when applicable.

**Comment by pretyman** [comment]
Actually, it is going to be sometime before this lands in upstream, I'll reopen this.

**Comment by ruslo** [comment]
I have no idea what is happening here :))) Can you add a link to upstream patch?

**Comment by ruslo** [comment]
Closing inactive pull request.

**Pull request closed without merging**
